name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: SQL Validation
        run: |
          echo "Checking SQL files for syntax errors..."
          grep -r "CREATE TABLE" --include="*.sql" .
          grep -r "ALTER TABLE" --include="*.sql" .
          echo "SQL validation completed"